#! /usr/bin/ruby

# The MIT License (MIT)
# Copyright (c) 2016-2019 Yukiya Nakagawa <yn.airscope@gmail.com>
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# The merge commit expression when a merge request accepted
MERGE_REQUEST_LOG_REGEXP = /commit [0-9a-f]+\nMerge: ([0-9a-f]{7,40}) ([0-9a-f]{7,40})\nAuthor: (.+)\nDate:   (.+)\n\n\s{4}Merge branch '(.+)' into '(.+)'\n\s{4}\n\s{4}(.+)\n[\s\S]+?See merge request [^!]*(![0-9]+)/

range = nil
if ARGV[0] == "-h" then
  puts "List of GitLab merge requests between the range expression like 'branch-a...branch-b' (with Markdown friendly list format).\n\n"
  puts "usage: git mr-diff mybranch...development"
  puts "    or git mr-diff (default: master...HEAD)"
  exit
elsif ARGV[0] then
  range = ARGV[0]
end

if range == nil then
  range = "master...HEAD"
end

puts "List merge requests for range: #{range}\n\n"

logs = `git rev-list --right-only #{range} | xargs git show -q`

mrlogs = []
logs.scan(MERGE_REQUEST_LOG_REGEXP) do |matched|
  mrlogs.push({:number => matched[7], :title => matched[6]})
end

mrlogs.sort! do |a, b|
  a[:number] <=> b[:number]
end

mrlogs.each do |mrlog|
  puts "* #{mrlog[:number]} #{mrlog[:title]}"
end
